/******************************************************************************/
/****        Generated by IBExpert 2015.12.21.1 21/07/2024 21:51:02        ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

CREATE DATABASE 'C:\Marcel\Projetos\Delphi\MeuPosto\Banco\DBMeuPosto.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_ABASTECIMENTO_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_ABASTECIMENTO_ID TO 0;

CREATE GENERATOR GEN_BOMBA_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_BOMBA_ID TO 0;

CREATE GENERATOR GEN_COMBUSTIVEL_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_COMBUSTIVEL_ID TO 0;

CREATE GENERATOR GEN_IMPOSTO_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_IMPOSTO_ID TO 0;

CREATE GENERATOR GEN_TANQUE_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_TANQUE_ID TO 0;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE ABASTECIMENTO (
    IDABASTECIMENTO          INTEGER NOT NULL,
    IDBOMBA                  INTEGER NOT NULL,
    IDCOMBUSTIVEL            INTEGER NOT NULL,
    IDIMPOSTO                INTEGER NOT NULL,
    QTDLITROS                INTEGER NOT NULL,
    DATAABASTECIMENTO        DATE,
    VALORABASTECIMENTO       DECIMAL(10,2) NOT NULL,
    VALORIMPOSTO             DECIMAL(10,2) NOT NULL,
    VALORFINALABASTECIMENTO  DECIMAL(10,2) NOT NULL
);

CREATE TABLE BOMBA (
    IDBOMBA    INTEGER NOT NULL,
    DESCRICAO  VARCHAR(100),
    IDTANQUE   INTEGER NOT NULL
);

CREATE TABLE COMBUSTIVEL (
    IDCOMBUSTIVEL  INTEGER NOT NULL,
    DESCRICAO      VARCHAR(100),
    VALORLITRO     DECIMAL(10,3)
);

CREATE TABLE IMPOSTO (
    IDIMPOSTO   INTEGER NOT NULL,
    DESCRICAO   VARCHAR(100),
    PERCENTUAL  NUMERIC(10,2)
);

CREATE TABLE TANQUE (
    IDTANQUE       INTEGER NOT NULL,
    DESCRICAO      VARCHAR(100),
    IDCOMBUSTIVEL  INTEGER NOT NULL
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT PK_ABASTECIMENTO PRIMARY KEY (IDABASTECIMENTO);
ALTER TABLE BOMBA ADD CONSTRAINT PK_BOMBA PRIMARY KEY (IDBOMBA);
ALTER TABLE COMBUSTIVEL ADD CONSTRAINT PK_COMBUSTIVEL PRIMARY KEY (IDCOMBUSTIVEL);
ALTER TABLE IMPOSTO ADD CONSTRAINT PK_IMPOSTO PRIMARY KEY (IDIMPOSTO);
ALTER TABLE TANQUE ADD CONSTRAINT PK_TANQUE PRIMARY KEY (IDTANQUE);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_ABASTECIMENTO_1 FOREIGN KEY (IDBOMBA) REFERENCES BOMBA (IDBOMBA);
ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_ABASTECIMENTO_2 FOREIGN KEY (IDCOMBUSTIVEL) REFERENCES COMBUSTIVEL (IDCOMBUSTIVEL);
ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_ABASTECIMENTO_3 FOREIGN KEY (IDIMPOSTO) REFERENCES IMPOSTO (IDIMPOSTO);
ALTER TABLE BOMBA ADD CONSTRAINT FK_BOMBA_1 FOREIGN KEY (IDTANQUE) REFERENCES TANQUE (IDTANQUE);
ALTER TABLE TANQUE ADD CONSTRAINT FK_TANQUE_1 FOREIGN KEY (IDCOMBUSTIVEL) REFERENCES COMBUSTIVEL (IDCOMBUSTIVEL);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: ABASTECIMENTO_BI */
CREATE TRIGGER ABASTECIMENTO_BI FOR ABASTECIMENTO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.idabastecimento is null) then
    new.idabastecimento = gen_id(gen_abastecimento_id,1);
end
^

/* Trigger: BOMBA_BI */
CREATE TRIGGER BOMBA_BI FOR BOMBA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.idbomba is null) then
    new.idbomba = gen_id(gen_bomba_id,1);
end
^

/* Trigger: COMBUSTIVEL_BI */
CREATE TRIGGER COMBUSTIVEL_BI FOR COMBUSTIVEL
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.idcombustivel is null) then
    new.idcombustivel = gen_id(gen_combustivel_id,1);
end
^

/* Trigger: IMPOSTO_BI */
CREATE TRIGGER IMPOSTO_BI FOR IMPOSTO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.idimposto is null) then
    new.idimposto = gen_id(gen_imposto_id,1);
end
^

/* Trigger: TANQUE_BI */
CREATE TRIGGER TANQUE_BI FOR TANQUE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.idtanque is null) then
    new.idtanque = gen_id(gen_tanque_id,1);
end
^
SET TERM ; ^

