INSERT INTO IMPOSTO (DESCRICAO, PERCENTUAL)
             VALUES ('IMPOSTO (13%)', 13);
INSERT INTO COMBUSTIVEL (DESCRICAO, VALORLITRO)
                 VALUES ('GASOLINA', 5.98);
INSERT INTO COMBUSTIVEL (DESCRICAO, VALORLITRO)
                 VALUES ('DIESEL', 4.5);
INSERT INTO TANQUE (DESCRICAO, IDCOMBUSTIVEL)
            VALUES ('TANQUE 1', 1);
INSERT INTO TANQUE (DESCRICAO, IDCOMBUSTIVEL)
            VALUES ('TANQUE 2', 2);
INSERT INTO BOMBA (DESCRICAO, IDTANQUE)
           VALUES ('BOMBA 01', 1);
INSERT INTO BOMBA (DESCRICAO, IDTANQUE)
           VALUES ('BOMBA 02', 1);
INSERT INTO BOMBA (DESCRICAO, IDTANQUE)
           VALUES ('BOMBA 03', 2);
INSERT INTO BOMBA (DESCRICAO, IDTANQUE)
           VALUES ('BOMBA 04', 2);

COMMIT WORK;

