INSERT INTO COMBUSTIVEL (IDCOMBUSTIVEL, DESCRICAO, VALORLITRO)
                 VALUES (1, 'ETANOL', 3.67);
INSERT INTO COMBUSTIVEL (IDCOMBUSTIVEL, DESCRICAO, VALORLITRO)
                 VALUES (2, 'GASOLINA', 5.98);
INSERT INTO COMBUSTIVEL (IDCOMBUSTIVEL, DESCRICAO, VALORLITRO)
                 VALUES (3, 'DIESEL', 4.5);

COMMIT WORK;
