INSERT INTO IMPOSTO (IDIMPOSTO, DESCRICAO, PERCENTUAL)
             VALUES (1, 'IMPOSTO ESPECIAL', 13);
INSERT INTO IMPOSTO (IDIMPOSTO, DESCRICAO, PERCENTUAL)
             VALUES (2, 'IMPOSTO DO MARCEL', 5.33);
INSERT INTO IMPOSTO (IDIMPOSTO, DESCRICAO, PERCENTUAL)
             VALUES (3, 'IMPOSTO DO PECADO', 27.6);

COMMIT WORK;
