INSERT INTO BOMBA (IDBOMBA, DESCRICAO, IDTANQUE)
           VALUES (1, 'BOMBA 01', 1);
INSERT INTO BOMBA (IDBOMBA, DESCRICAO, IDTANQUE)
           VALUES (2, 'BOMBA 02', 1);
INSERT INTO BOMBA (IDBOMBA, DESCRICAO, IDTANQUE)
           VALUES (3, 'BOMBA 03', 2);
INSERT INTO BOMBA (IDBOMBA, DESCRICAO, IDTANQUE)
           VALUES (4, 'BOMBA 04', 2);

COMMIT WORK;
